### ISSUE TITLE
views (folder)

### ISSUE THREAD

**Issue by ChrissieSparling** [bdibil/PNW-ArtSea#18]
- [x] Home Page
- [x]  Artist Dashboard 
- [x]  User Dashboard 
- [x]  Registry

**Comment by ChrissieSparling** [comment]
#

- [x] - layouts (subfolder)
- [x] - main.handlebars (file)
- [x] - partials (subfolder)
- [x] - login.handlebars (file)
- [x] - registry.handbars (file)
- [x] - artType.handlebars (file)
- [x] - homepage,handlebars (file)
- [x] - login.handlebars (file)
- [x] - artist.handlebars (file)
- [x] - category. handlebars ? (file)

**Comment by ChrissieSparling** [comment]
C:\Users\giggl\code\PNW-ArtSea\views\gallery.handlebars
C:\Users\giggl\code\PNW-ArtSea\views\homepage.handlebars
C:\Users\giggl\code\PNW-ArtSea\views\login.handlebars
C:\Users\giggl\code\PNW-ArtSea\views\painting.handlebars
C:\Users\giggl\code\PNW-ArtSea\views\signup.handlebars

**Comment by sinka27** [comment]
All handlebars created
