### ISSUE TITLE
Wireframe 

### ISSUE THREAD

**Issue by bdibil** [bdibil/PNW-ArtSea#3]

**Comment by ChrissieSparling** [comment]
![project 2 -landing page](https://user-images.githubusercontent.com/90416428/153106808-73111084-8c50-41f5-a885-8682dac17b63.png)
![project 2-artist page](https://user-images.githubusercontent.com/90416428/153106812-92dc5edf-007b-466a-bf0e-e7143d95eddf.png)
![project 2- Art Lovers](https://user-images.githubusercontent.com/90416428/153106828-589ad03d-11f3-41a0-9be8-313db6b42a18.png)


these wire-frames are completed!
