### ISSUE TITLE
Testing our MVP'S

### ISSUE THREAD

**Issue by ChrissieSparling** [bdibil/PNW-ArtSea#30]
- [beginning uploading our seed data into our seeds folders and our images into our images folder
- ] 

- [ join all connecting routes where applicable] 

- [ test all routes by running npm i terminal commands.] 
- trouble shoot any errors before uploading data to the dev branch.]
- 
- reach out for help once you've looked for the solution on your own and can't find it! ]

**Comment by sinka27** [comment]
Nodemailer tested by Parul
Cloudinary Tested by Bernardo
